version: '3.8'

services:
  dns-leak-app:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "53:53/udp"
    cap_add:
      - "NET_BIND_SERVICE"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOMAIN_NAME=${DOMAIN_NAME:-checkdnsleak.com}
      - VPS_IPV4=${VPS_IPV4:-23.95.215.125}
      - VPS_IPV6=${VPS_IPV6}
    networks:
      - dns-leak-net
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - dns-leak-net

networks:
  dns-leak-net:
    driver: bridge

volumes:
  redis-data: